name: main
on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
    - uses: actions/checkout@v2
    - name: Convert test file to png image
      uses: Burnett01/actions-drawio@1.2
      with:
        src:  nc-reactor-debug-chart.drawio.xml
        dest: test.png
    - name: jpeg
      uses: ./
      with:
        src:  nc-reactor-debug-chart.drawio.xml
        dest: test.jpeg
    - name: make release
      id: create_release
      uses:  actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      with:
        tag_name: test
        release_name: test
        
        
